doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # 'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'DomainMeasurementMigrations': '%kernel.project_dir%/src/Domain/Measurement/migrations'
        'DomainSensorMigrations': '%kernel.project_dir%/src/Domain/Sensor/migrations'
        'DomainUserMigrations': '%kernel.project_dir%/src/Domain/User/migrations'
        'DomainWineMigrations': '%kernel.project_dir%/src/Domain/Wine/migrations'
    enable_profiler: false
